In [55]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [56]:
dam = pd.read_csv("lg_aimers_5th/data/Dam dispensing.csv")
target = pd.read_csv("lg_aimers_5th/data/train_y.csv")

merged_dam = pd.merge(dam, target, "inner", on="Set ID")

/tmp/ipykernel_87905/3844665012.py:1: DtypeWarning: Columns (62,64) have mixed types. Specify dtype option on import or set low_memory=False.
  dam = pd.read_csv("lg_aimers_5th/data/Dam dispensing.csv")

In [57]:
pd.set_option('display.max_rows', None)
merged_dam.isnull().sum()

Wip Line                 0
Process Desc.            0
Equipment                0
Model.Suffix             0
Workorder                0
LOT ID                   0
Set ID                   0
Box ID               42769
Collect Date             0
Insp. Seq No.            0
Insp Judge Code          0
Collect Result           0
Unit Time            42769
Judge Value          42769
Collect Result.1         0
Unit Time.1          42769
Judge Value.1        42769
Collect Result.2         0
Unit Time.2          42769
Judge Value.2        42769
Collect Result.3         0
Unit Time.3          42769
Judge Value.3        42769
Collect Result.4         0
Unit Time.4          42769
Judge Value.4        42769
Collect Result.5         0
Unit Time.5          42769
Judge Value.5        42769
Collect Result.6         0
Unit Time.6          42769
Judge Value.6        42769
Collect Result.7         0
Unit Time.7          42769
Judge Value.7        42769
Collect Result.8         0
Unit Time.8          42769
Judge Value.8        42769
Collect Result.9         0
Unit Time.9          42769
Judge Value.9        42769
Collect Result.10        0
Unit Time.10         42769
Judge Value.10       42769
Collect Result.11        0
Unit Time.11         42769
Judge Value.11       42769
Collect Result.12        0
Unit Time.12         42769
Judge Value.12       42769
Collect Result.13        0
Unit Time.13         42769
Judge Value.13       42769
Collect Result.14        0
Unit Time.14         42769
Judge Value.14       42769
Collect Result.15        0
Unit Time.15         42769
Judge Value.15       42769
Collect Result.16        0
Unit Time.16         42769
Judge Value.16       42769
Collect Result.17    13320
Unit Time.17         42769
Judge Value.17       30989
Collect Result.18        0
Unit Time.18         42769
Judge Value.18       42769
Collect Result.19        0
Unit Time.19         42769
Judge Value.19       42769
Collect Result.20        0
Unit Time.20         42769
Judge Value.20       42769
Collect Result.21        0
Unit Time.21         42769
Judge Value.21       42769
Collect Result.22        0
Unit Time.22         42769
Judge Value.22       42769
Collect Result.23        0
Unit Time.23         42769
Judge Value.23       42769
Collect Result.24        0
Unit Time.24         42769
Judge Value.24       42769
Collect Result.25        0
Unit Time.25         42769
Judge Value.25       42769
Collect Result.26        0
Unit Time.26         42769
Judge Value.26       42769
Collect Result.27        0
Unit Time.27         42769
Judge Value.27       42769
Collect Result.28        0
Unit Time.28         42769
Judge Value.28       42769
Collect Result.29        0
Unit Time.29         42769
Judge Value.29       42769
Collect Result.30        0
Unit Time.30         42769
Judge Value.30       42769
Collect Result.31        0
Unit Time.31         42769
Judge Value.31       42769
Collect Result.32        0
Unit Time.32         42769
Judge Value.32       42769
Collect Result.33        0
Unit Time.33         42769
Judge Value.33       42769
Collect Result.34        0
Unit Time.34         42769
Judge Value.34       42769
Collect Result.35        0
Unit Time.35         42769
Judge Value.35       42769
Collect Result.36        0
Unit Time.36         42769
Judge Value.36       42769
Collect Result.37        0
Unit Time.37         42769
Judge Value.37       42769
Collect Result.38        0
Unit Time.38         42769
Judge Value.38       42769
Collect Result.39        0
Unit Time.39         42769
Judge Value.39       42769
Collect Result.40        0
Unit Time.40         42769
Judge Value.40       42769
Collect Result.41        0
Unit Time.41         42769
Judge Value.41       42769
Collect Result.42        0
Unit Time.42         42769
Judge Value.42       42769
Collect Result.43        0
Unit Time.43         42769
Judge Value.43       42769
Collect Result.44        0
Unit Time.44         42769
Judge Value.44       42769
Collect Result.45        0
Unit Time.45         42769
Judge Value.45       42769
Collect Result.46        0
Unit Time.46         42769
Judge Value.46       42769
Collect Result.47        0
Unit Time.47         42769
Judge Value.47       42769
Collect Result.48        0
Unit Time.48         42769
Judge Value.48       42769
Collect Result.49        0
Unit Time.49         42769
Judge Value.49       42769
Collect Result.50        0
Unit Time.50         42769
Judge Value.50       42769
Collect Result.51        0
Unit Time.51         42769
Judge Value.51       42769
Collect Result.52        0
Unit Time.52         42769
Judge Value.52       42769
Collect Result.53        0
Unit Time.53         42769
Judge Value.53       42769
Collect Result.54        0
Unit Time.54         42769
Judge Value.54       42769
Collect Result.55        0
Unit Time.55         42769
Judge Value.55       42769
Collect Result.56        0
Unit Time.56         42769
Judge Value.56       42769
Collect Result.57        0
Unit Time.57         42769
Judge Value.57       42769
Collect Result.58        0
Unit Time.58         42769
Judge Value.58       42769
Collect Result.59        0
Unit Time.59         42769
Judge Value.59       42769
Collect Result.60        0
Unit Time.60         42769
Judge Value.60       42769
Collect Result.61        0
Unit Time.61         42769
Judge Value.61       42769
Collect Result.62        0
Unit Time.62         42769
Judge Value.62       42769
Collect Result.63        0
Unit Time.63         42769
Judge Value.63       42769
Collect Result.64        0
Unit Time.64         42769
Judge Value.64       42769
Collect Result.65        0
Unit Time.65         42769
Judge Value.65       42769
Collect Result.66        0
Unit Time.66         42769
Judge Value.66       42769
Collect Result.67        0
Unit Time.67         42769
Judge Value.67       42769
Collect Result.68        0
Unit Time.68         42769
Judge Value.68       42769
Collect Result.69        0
Unit Time.69         42769
Judge Value.69       42769
Unnamed: 221         17669
target                   0
dtype: int64

In [58]:
merged_dam.columns

Index(['Wip Line', 'Process Desc.', 'Equipment', 'Model.Suffix', 'Workorder',
       'LOT ID', 'Set ID', 'Box ID', 'Collect Date', 'Insp. Seq No.',
       ...
       'Unit Time.67', 'Judge Value.67', 'Collect Result.68', 'Unit Time.68',
       'Judge Value.68', 'Collect Result.69', 'Unit Time.69', 'Judge Value.69',
       'Unnamed: 221', 'target'],
      dtype='object', length=223)

In [59]:
# drop_cols = []
# for column in merged_dam.columns:
#     if (merged_dam[column].notnull().sum() // 2) < merged_dam[
#         column
#     ].isnull().sum():
#         drop_cols.append(column)
# merged_dam = merged_dam.drop(drop_cols, axis=1)

In [60]:
drop_cols = []
for column in merged_dam.columns:
    if merged_dam[column].isnull().sum() > 18000:
        drop_cols.append(column)
merged_dam = merged_dam.drop(drop_cols, axis=1)

In [61]:
merged_dam.isnull().sum()

Wip Line                 0
Process Desc.            0
Equipment                0
Model.Suffix             0
Workorder                0
LOT ID                   0
Set ID                   0
Collect Date             0
Insp. Seq No.            0
Insp Judge Code          0
Collect Result           0
Collect Result.1         0
Collect Result.2         0
Collect Result.3         0
Collect Result.4         0
Collect Result.5         0
Collect Result.6         0
Collect Result.7         0
Collect Result.8         0
Collect Result.9         0
Collect Result.10        0
Collect Result.11        0
Collect Result.12        0
Collect Result.13        0
Collect Result.14        0
Collect Result.15        0
Collect Result.16        0
Collect Result.17    13320
Collect Result.18        0
Collect Result.19        0
Collect Result.20        0
Collect Result.21        0
Collect Result.22        0
Collect Result.23        0
Collect Result.24        0
Collect Result.25        0
Collect Result.26        0
Collect Result.27        0
Collect Result.28        0
Collect Result.29        0
Collect Result.30        0
Collect Result.31        0
Collect Result.32        0
Collect Result.33        0
Collect Result.34        0
Collect Result.35        0
Collect Result.36        0
Collect Result.37        0
Collect Result.38        0
Collect Result.39        0
Collect Result.40        0
Collect Result.41        0
Collect Result.42        0
Collect Result.43        0
Collect Result.44        0
Collect Result.45        0
Collect Result.46        0
Collect Result.47        0
Collect Result.48        0
Collect Result.49        0
Collect Result.50        0
Collect Result.51        0
Collect Result.52        0
Collect Result.53        0
Collect Result.54        0
Collect Result.55        0
Collect Result.56        0
Collect Result.57        0
Collect Result.58        0
Collect Result.59        0
Collect Result.60        0
Collect Result.61        0
Collect Result.62        0
Collect Result.63        0
Collect Result.64        0
Collect Result.65        0
Collect Result.66        0
Collect Result.67        0
Collect Result.68        0
Collect Result.69        0
Unnamed: 221         17669
target                   0
dtype: int64

In [66]:
merged_dam.iloc[17669:,27:80] = merged_dam.iloc[17669:,28:81]

/tmp/ipykernel_87905/3633679323.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0. 0. 0. ... 0. 0. 0.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  merged_dam.iloc[17669:,27:80] = merged_dam.iloc[17669:,28:81]

In [78]:
merged_dam.iloc[42000,27]

550.5

In [74]:
merged_dam.isnull().sum()

Wip Line                 0
Process Desc.            0
Equipment                0
Model.Suffix             0
Workorder                0
LOT ID                   0
Set ID                   0
Collect Date             0
Insp. Seq No.            0
Insp Judge Code          0
Collect Result           0
Collect Result.1         0
Collect Result.2         0
Collect Result.3         0
Collect Result.4         0
Collect Result.5         0
Collect Result.6         0
Collect Result.7         0
Collect Result.8         0
Collect Result.9         0
Collect Result.10        0
Collect Result.11        0
Collect Result.12        0
Collect Result.13        0
Collect Result.14        0
Collect Result.15        0
Collect Result.16        0
Collect Result.17        0
Collect Result.18        0
Collect Result.19        0
Collect Result.20        0
Collect Result.21        0
Collect Result.22        0
Collect Result.23        0
Collect Result.24        0
Collect Result.25        0
Collect Result.26        0
Collect Result.27        0
Collect Result.28        0
Collect Result.29        0
Collect Result.30        0
Collect Result.31        0
Collect Result.32        0
Collect Result.33        0
Collect Result.34        0
Collect Result.35        0
Collect Result.36        0
Collect Result.37        0
Collect Result.38        0
Collect Result.39        0
Collect Result.40        0
Collect Result.41        0
Collect Result.42        0
Collect Result.43        0
Collect Result.44        0
Collect Result.45        0
Collect Result.46        0
Collect Result.47        0
Collect Result.48        0
Collect Result.49        0
Collect Result.50        0
Collect Result.51        0
Collect Result.52        0
Collect Result.53        0
Collect Result.54        0
Collect Result.55        0
Collect Result.56        0
Collect Result.57        0
Collect Result.58        0
Collect Result.59        0
Collect Result.60        0
Collect Result.61        0
Collect Result.62        0
Collect Result.63        0
Collect Result.64        0
Collect Result.65        0
Collect Result.66        0
Collect Result.67        0
Collect Result.68        0
Collect Result.69        0
Unnamed: 221         17669
target                   0
dtype: int64

In [81]:
merged_dam = merged_dam.drop(columns='Unnamed: 221')

In [82]:
merged_dam.isnull().sum()

Wip Line             0
Process Desc.        0
Equipment            0
Model.Suffix         0
Workorder            0
LOT ID               0
Set ID               0
Collect Date         0
Insp. Seq No.        0
Insp Judge Code      0
Collect Result       0
Collect Result.1     0
Collect Result.2     0
Collect Result.3     0
Collect Result.4     0
Collect Result.5     0
Collect Result.6     0
Collect Result.7     0
Collect Result.8     0
Collect Result.9     0
Collect Result.10    0
Collect Result.11    0
Collect Result.12    0
Collect Result.13    0
Collect Result.14    0
Collect Result.15    0
Collect Result.16    0
Collect Result.17    0
Collect Result.18    0
Collect Result.19    0
Collect Result.20    0
Collect Result.21    0
Collect Result.22    0
Collect Result.23    0
Collect Result.24    0
Collect Result.25    0
Collect Result.26    0
Collect Result.27    0
Collect Result.28    0
Collect Result.29    0
Collect Result.30    0
Collect Result.31    0
Collect Result.32    0
Collect Result.33    0
Collect Result.34    0
Collect Result.35    0
Collect Result.36    0
Collect Result.37    0
Collect Result.38    0
Collect Result.39    0
Collect Result.40    0
Collect Result.41    0
Collect Result.42    0
Collect Result.43    0
Collect Result.44    0
Collect Result.45    0
Collect Result.46    0
Collect Result.47    0
Collect Result.48    0
Collect Result.49    0
Collect Result.50    0
Collect Result.51    0
Collect Result.52    0
Collect Result.53    0
Collect Result.54    0
Collect Result.55    0
Collect Result.56    0
Collect Result.57    0
Collect Result.58    0
Collect Result.59    0
Collect Result.60    0
Collect Result.61    0
Collect Result.62    0
Collect Result.63    0
Collect Result.64    0
Collect Result.65    0
Collect Result.66    0
Collect Result.67    0
Collect Result.68    0
Collect Result.69    0
target               0
dtype: int64

In [ ]:
#EDA

In [85]:
merged_dam['Collect Result.17'].value_counts()

Collect Result.17
549      7954
162.4    7358
550.3    3909
550.0    2585
162.7    2581
550.4    2475
164.2    2462
550.6    1833
551.5    1505
549.5    1363
551.7    1031
548.9     867
161.2     847
550.5     786
163.5     588
164.1     543
552.1     517
161.7     512
551.8     503
549.4     470
552.0     466
164.5     397
163.3     260
163.8     223
164.0     222
551.3     133
551.2     103
163.4      67
550.7      67
163.7      38
163.0      30
548.5      26
551.6      25
163.6      13
163.1       9
551.0       1
Name: count, dtype: int64

In [86]:
merged_dam['Collect Result.18'].value_counts()

Collect Result.18
463.00    7453
467.10    2873
465.30    2623
463.50    2585
465.70    2543
463.70    2472
465.50    2399
463.80    2208
465.00    2160
465.40    1975
463.90    1832
465.10    1825
463.60    1701
462.50    1386
462.20     909
464.20     847
464.30     786
466.20     556
464.70     512
462.70     470
462.75     462
465.80     409
467.50     369
466.90     338
466.70     260
466.00     246
464.60     132
464.80     105
466.30      81
464.00      70
465.60      57
466.10      38
467.20      28
464.90      25
466.80      16
466.60      13
466.40       3
464.10       1
466.50       1
Name: count, dtype: int64

In [87]:
merged_dam['Collect Result.19'].value_counts()

Collect Result.19
160.5    8298
552.0    4976
160.8    3647
551.3    2982
161.3    2542
553.6    2462
160.0    2204
162.3    2022
551.7    1975
161.5    1832
162.6    1534
159.5    1426
553.4    1119
159.8     867
550.5     847
161.4     787
553.1     572
551.0     512
160.3     470
162.9     466
161.2     262
552.9     259
553.2     222
162.2     132
162.1     104
552.3      67
552.6      46
552.4      39
553.0      38
554.0      27
162.5      25
552.7       3
551.1       2
552.2       1
553.7       1
161.9       1
Name: count, dtype: int64