In [62]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('train_data_mlp.csv')

In [63]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import backend as K
from sklearn.metrics import f1_score
import numpy as np

tf.random.set_seed(42)

#F1 스코어를 계산하는 사용자 정의 함수
def f1_m(y_true, y_pred):
    y_pred = K.round(y_pred)
    tp = K.sum(K.cast(y_true * y_pred, 'float'), axis=0)
    tn = K.sum(K.cast((1-y_true) * (1-y_pred), 'float'), axis=0)
    fp = K.sum(K.cast((1-y_true) * y_pred, 'float'), axis=0)
    fn = K.sum(K.cast(y_true * (1-y_pred), 'float'), axis=0)

    p = tp / (tp + fp + K.epsilon())
    r = tp / (tp + fn + K.epsilon())

    f1 = 2 * p * r / (p + r + K.epsilon())
    f1 = tf.where(tf.math.is_nan(f1), tf.zeros_like(f1), f1)
    return K.mean(f1)

# 모델 생성
model_dam = Sequential()
model_dam.add(Dense(40, input_dim=55, activation='relu'))
model_dam.add(Dense(25, activation='relu'))
model_dam.add(Dense(10, activation='relu'))
model_dam.add(Dense(1, activation='sigmoid'))

# F1 스코어를 평가지표로 사용
model_dam.compile(optimizer='adam', loss='binary_crossentropy', metrics=[f1_m])

model_dam.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 40)                2240

 dense_17 (Dense)            (None, 25)                1025

 dense_18 (Dense)            (None, 10)                260

 dense_19 (Dense)            (None, 1)                 11

=================================================================
Total params: 3536 (13.81 KB)
Trainable params: 3536 (13.81 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [64]:
tf.random.set_seed(12)
# 모델 생성
model_autoclave = Sequential()
model_autoclave.add(Dense(7, input_dim=9, activation='relu'))
model_autoclave.add(Dense(5, activation='relu'))
model_autoclave.add(Dense(3, activation='relu'))
model_autoclave.add(Dense(1, activation='sigmoid'))

# F1 스코어를 평가지표로 사용
model_autoclave.compile(optimizer='adam', loss='binary_crossentropy', metrics=[f1_m])

model_autoclave.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_20 (Dense)            (None, 7)                 70

 dense_21 (Dense)            (None, 5)                 40

 dense_22 (Dense)            (None, 3)                 18

 dense_23 (Dense)            (None, 1)                 4

=================================================================
Total params: 132 (528.00 Byte)
Trainable params: 132 (528.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [65]:
tf.random.set_seed(34)
# 모델 생성
model_fill1 = Sequential()
model_fill1.add(Dense(13, input_dim=19, activation='relu'))
model_fill1.add(Dense(8, activation='relu'))
model_fill1.add(Dense(4, activation='relu'))
model_fill1.add(Dense(1, activation='sigmoid'))

# F1 스코어를 평가지표로 사용
model_fill1.compile(optimizer='adam', loss='binary_crossentropy', metrics=[f1_m])

model_fill1.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 13)                260

 dense_25 (Dense)            (None, 8)                 112

 dense_26 (Dense)            (None, 4)                 36

 dense_27 (Dense)            (None, 1)                 5

=================================================================
Total params: 413 (1.61 KB)
Trainable params: 413 (1.61 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [66]:
tf.random.set_seed(25)
# 모델 생성
model_fill2 = Sequential()
model_fill2.add(Dense(13, input_dim=18, activation='relu'))
model_fill2.add(Dense(8, activation='relu'))
model_fill2.add(Dense(4, activation='relu'))
model_fill2.add(Dense(1, activation='sigmoid'))

# F1 스코어를 평가지표로 사용
model_fill2.compile(optimizer='adam', loss='binary_crossentropy', metrics=[f1_m])

model_fill2.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_28 (Dense)            (None, 13)                247

 dense_29 (Dense)            (None, 8)                 112

 dense_30 (Dense)            (None, 4)                 36

 dense_31 (Dense)            (None, 1)                 5

=================================================================
Total params: 400 (1.56 KB)
Trainable params: 400 (1.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [67]:
X = df.drop(columns=['target'])
Y = df['target']

In [68]:
X

,CURE END POSITION X Collect Result_Dam,CURE END POSITION Z Collect Result_Dam,CURE END POSITION Θ Collect Result_Dam,CURE SPEED Collect Result_Dam,CURE START POSITION X Collect Result_Dam,CURE START POSITION Θ Collect Result_Dam,DISCHARGED SPEED OF RESIN Collect Result_Dam,DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam,DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam,DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam,...,HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill2,Head Purge Position Z Collect Result_Fill2,Machine Tact time Collect Result_Fill2,suffix_encoded
0,240.0,2.5,-90,100,1030,-90,16,14.9,8.4,14.7,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,114.612,19.9,3
1,240.0,2.5,-90,70,1030,-90,10,21.3,4.9,21.3,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.6,3
2,1000.0,12.5,90,85,280,90,16,14.7,8.5,14.7,...,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,114.612,19.8,0
3,1000.0,12.5,90,70,280,90,10,21.3,8.4,21.3,...,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,85.000,19.9,0
4,240.0,2.5,-90,70,1030,-90,10,9.7,4.9,9.6,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,240.0,2.5,-90,70,1030,-90,10,17.0,5.0,17.0,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.2,0
40502,1000.0,12.5,90,100,280,90,16,14.9,8.5,14.7,...,692.8,1324.2,1324.2,1324.2,243.5,243.5,243.5,114.612,20.5,0
40503,240.0,2.5,-90,100,1030,-90,16,14.2,8.2,14.3,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.7,0
40504,1000.0,12.5,90,70,280,90,10,9.7,4.9,9.7,...,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,85.000,20.1,0
40505,240.0,2.5,-90,70,1030,-90,10,9.6,3.9,9.7,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.4,0

In [69]:
Y

0        1
1        1
2        1
3        1
4        1
        ..
40501    1
40502    1
40503    1
40504    1
40505    0
Name: target, Length: 40506, dtype: int64

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40506 entries, 0 to 40505
Data columns (total 99 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   CURE END POSITION X Collect Result_Dam                      40506 non-null  float64
 1   CURE END POSITION Z Collect Result_Dam                      40506 non-null  float64
 2   CURE END POSITION Θ Collect Result_Dam                      40506 non-null  int64
 3   CURE SPEED Collect Result_Dam                               40506 non-null  int64
 4   CURE START POSITION X Collect Result_Dam                    40506 non-null  int64
 5   CURE START POSITION Θ Collect Result_Dam                    40506 non-null  int64
 6   DISCHARGED SPEED OF RESIN Collect Result_Dam                40506 non-null  int64
 7   DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam         40506 non-null  float64
 8   DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam         40506 non-null  float64
 9   DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam         40506 non-null  float64
 10  Dispense Volume(Stage1) Collect Result_Dam                  40506 non-null  float64
 11  Dispense Volume(Stage2) Collect Result_Dam                  40506 non-null  float64
 12  Dispense Volume(Stage3) Collect Result_Dam                  40506 non-null  float64
 13  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Dam    40506 non-null  float64
 14  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Dam    40506 non-null  float64
 15  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Dam    40506 non-null  float64
 16  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam    40506 non-null  float64
 17  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Dam    40506 non-null  float64
 18  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam    40506 non-null  float64
 19  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Dam    40506 non-null  float64
 20  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Dam    40506 non-null  float64
 21  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Dam    40506 non-null  float64
 22  Head Clean Position Z Collect Result_Dam                    40506 non-null  float64
 23  Head Purge Position Z Collect Result_Dam                    40506 non-null  float64
 24  Head Zero Position Y Collect Result_Dam                     40506 non-null  float64
 25  Head Zero Position Z Collect Result_Dam                     40506 non-null  float64
 26  Machine Tact time Collect Result_Dam                        40506 non-null  float64
 27  Stage1 Circle1 Distance Speed Collect Result_Dam            40506 non-null  float64
 28  Stage1 Circle2 Distance Speed Collect Result_Dam            40506 non-null  float64
 29  Stage1 Circle3 Distance Speed Collect Result_Dam            40506 non-null  float64
 30  Stage1 Circle4 Distance Speed Collect Result_Dam            40506 non-null  float64
 31  Stage1 Line1 Distance Speed Collect Result_Dam              40506 non-null  float64
 32  Stage1 Line2 Distance Speed Collect Result_Dam              40506 non-null  float64
 33  Stage1 Line3 Distance Speed Collect Result_Dam              40506 non-null  float64
 34  Stage1 Line4 Distance Speed Collect Result_Dam              40506 non-null  float64
 35  Stage2 Circle1 Distance Speed Collect Result_Dam            40506 non-null  float64
 36  Stage2 Circle2 Distance Speed Collect Result_Dam            40506 non-null  float64
 37  Stage2 Circle3 Distance Speed Collect Result_Dam            40506 non-null  float64
 38  Stage2 Circle4 Distance Speed Collect Result_Dam            40506 non-null  float64
 39  Stage2 Line1 Distance Speed Collect Result_Dam              40506 non-null  float64
 40  Stage2 Line2 Distance Speed Collect Result_Dam              40506 non-null  float64
 41  Stage2 Line3 Distance Speed Collect Result_Dam              40506 non-null  float64
 42  Stage2 Line4 Distance Speed Collect Result_Dam              40506 non-null  float64
 43  Stage3 Circle1 Distance Speed Collect Result_Dam            40506 non-null  float64
 44  Stage3 Circle2 Distance Speed Collect Result_Dam            40506 non-null  float64
 45  Stage3 Circle3 Distance Speed Collect Result_Dam            40506 non-null  float64
 46  Stage3 Circle4 Distance Speed Collect Result_Dam            40506 non-null  float64
 47  Stage3 Line1 Distance Speed Collect Result_Dam              40506 non-null  float64
 48  Stage3 Line2 Distance Speed Collect Result_Dam              40506 non-null  float64
 49  Stage3 Line3 Distance Speed Collect Result_Dam              40506 non-null  float64
 50  Stage3 Line4 Distance Speed Collect Result_Dam              40506 non-null  float64
 51  THICKNESS 1 Collect Result_Dam                              40506 non-null  float64
 52  THICKNESS 2 Collect Result_Dam                              40506 non-null  float64
 53  THICKNESS 3 Collect Result_Dam                              40506 non-null  float64
 54  1st Pressure Collect Result_AutoClave                       40506 non-null  float64
 55  1st Pressure 1st Pressure Unit Time_AutoClave               40506 non-null  int64
 56  2nd Pressure Collect Result_AutoClave                       40506 non-null  float64
 57  2nd Pressure Unit Time_AutoClave                            40506 non-null  int64
 58  3rd Pressure Collect Result_AutoClave                       40506 non-null  float64
 59  3rd Pressure Unit Time_AutoClave                            40506 non-null  int64
 60  Chamber Temp. Collect Result_AutoClave                      40506 non-null  int64
 61  Chamber Temp. Unit Time_AutoClave                           40506 non-null  int64
 62  DISCHARGED SPEED OF RESIN Collect Result_Fill1              40506 non-null  float64
 63  DISCHARGED TIME OF RESIN(Stage1) Collect Result_Fill1       40506 non-null  float64
 64  DISCHARGED TIME OF RESIN(Stage2) Collect Result_Fill1       40506 non-null  float64
 65  DISCHARGED TIME OF RESIN(Stage3) Collect Result_Fill1       40506 non-null  float64
 66  Dispense Volume(Stage1) Collect Result_Fill1                40506 non-null  float64
 67  Dispense Volume(Stage2) Collect Result_Fill1                40506 non-null  float64
 68  Dispense Volume(Stage3) Collect Result_Fill1                40506 non-null  float64
 69  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill1  40506 non-null  float64
 70  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill1  40506 non-null  float64
 71  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill1  40506 non-null  float64
 72  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill1  40506 non-null  float64
 73  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill1  40506 non-null  float64
 74  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill1  40506 non-null  float64
 75  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill1  40506 non-null  float64
 76  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill1  40506 non-null  float64
 77  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill1  40506 non-null  float64
 78  Head Purge Position Z Collect Result_Fill1                  40506 non-null  float64
 79  Machine Tact time Collect Result_Fill1                      40506 non-null  float64
 80  CURE END POSITION X Collect Result_Fill2                    40506 non-null  int64
 81  CURE END POSITION Z Collect Result_Fill2                    40506 non-null  int64
 82  CURE SPEED Collect Result_Fill2                             40506 non-null  int64
 83  CURE STANDBY POSITION Z Collect Result_Fill2                40506 non-null  int64
 84  CURE START POSITION X Collect Result_Fill2                  40506 non-null  int64
 85  CURE START POSITION Z Collect Result_Fill2                  40506 non-null  int64
 86  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill2  40506 non-null  float64
 87  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill2  40506 non-null  float64
 88  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill2  40506 non-null  float64
 89  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill2  40506 non-null  float64
 90  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill2  40506 non-null  float64
 91  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill2  40506 non-null  float64
 92  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill2  40506 non-null  float64
 93  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill2  40506 non-null  float64
 94  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill2  40506 non-null  float64
 95  Head Purge Position Z Collect Result_Fill2                  40506 non-null  float64
 96  Machine Tact time Collect Result_Fill2                      40506 non-null  float64
 97  target                                                      40506 non-null  int64
 98  suffix_encoded                                              40506 non-null  int64
dtypes: float64(81), int64(18)
memory usage: 30.6 MB

In [71]:
X_dam = X.iloc[:,0:54]
X_dam['suffix_encoded'] = X['suffix_encoded']

In [72]:
X_autoclave = X.iloc[:,54:62]
X_autoclave['suffix_encoded'] = X['suffix_encoded']

In [73]:
X_fill1 = X.iloc[:,62:80]
X_fill1['suffix_encoded'] = X['suffix_encoded']

In [74]:
X_fill2 = X.iloc[:,80:]
X_fill2

,CURE END POSITION X Collect Result_Fill2,CURE END POSITION Z Collect Result_Fill2,CURE SPEED Collect Result_Fill2,CURE STANDBY POSITION Z Collect Result_Fill2,CURE START POSITION X Collect Result_Fill2,CURE START POSITION Z Collect Result_Fill2,HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill2,HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill2,HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill2,Head Purge Position Z Collect Result_Fill2,Machine Tact time Collect Result_Fill2,suffix_encoded
0,240,33,48,33,1020,33,835.5,458.0,156.0,428.0,427.9,428.0,243.7,243.7,243.7,114.612,19.9,3
1,240,33,50,33,1020,33,835.5,458.0,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.6,3
2,240,33,50,33,1020,33,305.0,499.8,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,114.612,19.8,0
3,240,33,50,33,1020,33,305.0,499.8,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,85.000,19.9,0
4,240,32,50,33,1020,33,835.5,458.0,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,240,33,50,33,1020,33,835.5,458.0,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.2,0
40502,240,33,48,33,1020,33,304.8,499.8,692.8,1324.2,1324.2,1324.2,243.5,243.5,243.5,114.612,20.5,0
40503,240,33,50,33,1020,33,835.5,458.0,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.7,0
40504,240,33,50,33,1020,33,305.0,499.8,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,85.000,20.1,0
40505,240,32,50,32,1020,32,835.5,458.0,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.4,0

In [75]:
from sklearn.model_selection import train_test_split

x_train_dam, x_valid_dam, y_train_dam, y_valid_dam = train_test_split(X_dam, Y, test_size=0.2, shuffle=True, stratify=Y, random_state=34)

In [76]:
history1 = model_dam.fit(x_train_dam, y_train_dam, epochs=10, validation_data=(x_valid_dam, y_valid_dam))

Epoch 1/10
1013/1013 [==============================] - 3s 2ms/step - loss: 5.9636 - f1_m: 0.9298 - val_loss: 4.1336 - val_f1_m: 0.9697
Epoch 2/10
1013/1013 [==============================] - 2s 2ms/step - loss: 1.8865 - f1_m: 0.9359 - val_loss: 0.3602 - val_f1_m: 0.9694
Epoch 3/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.7648 - f1_m: 0.9467 - val_loss: 0.4659 - val_f1_m: 0.9697
Epoch 4/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.9981 - f1_m: 0.9494 - val_loss: 4.8226 - val_f1_m: 0.9697
Epoch 5/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.5249 - f1_m: 0.9576 - val_loss: 0.2499 - val_f1_m: 0.9697
Epoch 6/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2573 - f1_m: 0.9689 - val_loss: 0.2502 - val_f1_m: 0.9685
Epoch 7/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.6596 - f1_m: 0.9646 - val_loss: 0.2367 - val_f1_m: 0.9697
Epoch 8/10
1013/1013 [==============================] - 3s 3ms/step - loss: 0.2293 - f1_m: 0.9696 - val_loss: 0.2253 - val_f1_m: 0.9697
Epoch 9/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2252 - f1_m: 0.9696 - val_loss: 0.2211 - val_f1_m: 0.9697
Epoch 10/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2278 - f1_m: 0.9696 - val_loss: 0.2215 - val_f1_m: 0.9697

In [77]:
x_train_autoclave, x_valid_autoclave, y_train_autoclave, y_valid_autoclave = train_test_split(X_autoclave, Y, test_size=0.2, shuffle=True, stratify=Y, random_state=34)

history2 = model_autoclave.fit(x_train_autoclave, y_train_autoclave, epochs=10, validation_data=(x_valid_autoclave, y_valid_autoclave))

Epoch 1/10
1013/1013 [==============================] - 3s 2ms/step - loss: 0.3887 - f1_m: 0.9670 - val_loss: 0.2496 - val_f1_m: 0.9698
Epoch 2/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2352 - f1_m: 0.9695 - val_loss: 0.2273 - val_f1_m: 0.9697
Epoch 3/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2253 - f1_m: 0.9696 - val_loss: 0.2308 - val_f1_m: 0.9697
Epoch 4/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2242 - f1_m: 0.9696 - val_loss: 0.2230 - val_f1_m: 0.9697
Epoch 5/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2237 - f1_m: 0.9697 - val_loss: 0.2219 - val_f1_m: 0.9697
Epoch 6/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2238 - f1_m: 0.9696 - val_loss: 0.2392 - val_f1_m: 0.9697
Epoch 7/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2238 - f1_m: 0.9696 - val_loss: 0.2218 - val_f1_m: 0.9697
Epoch 8/10
1013/1013 [==============================] - 3s 3ms/step - loss: 0.2234 - f1_m: 0.9696 - val_loss: 0.2232 - val_f1_m: 0.9697
Epoch 9/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2230 - f1_m: 0.9696 - val_loss: 0.2205 - val_f1_m: 0.9697
Epoch 10/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2231 - f1_m: 0.9696 - val_loss: 0.2206 - val_f1_m: 0.9697

In [78]:
x_train_fill1, x_valid_fill1, y_train_fill1, y_valid_fill1 = train_test_split(X_fill1, Y, test_size=0.2, shuffle=True, stratify=Y, random_state=34)

history3 = model_fill1.fit(x_train_fill1, y_train_fill1, epochs=10, validation_data=(x_valid_fill1, y_valid_fill1))

Epoch 1/10
1013/1013 [==============================] - 3s 2ms/step - loss: 1.0844 - f1_m: 0.9611 - val_loss: 0.2622 - val_f1_m: 0.9689
Epoch 2/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2727 - f1_m: 0.9682 - val_loss: 0.2748 - val_f1_m: 0.9592
Epoch 3/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2598 - f1_m: 0.9693 - val_loss: 0.2348 - val_f1_m: 0.9697
Epoch 4/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2579 - f1_m: 0.9693 - val_loss: 0.2415 - val_f1_m: 0.9697
Epoch 5/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2561 - f1_m: 0.9691 - val_loss: 0.2930 - val_f1_m: 0.9689
Epoch 6/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2518 - f1_m: 0.9695 - val_loss: 0.2317 - val_f1_m: 0.9697
Epoch 7/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2463 - f1_m: 0.9695 - val_loss: 0.3066 - val_f1_m: 0.9698
Epoch 8/10
1013/1013 [==============================] - 3s 3ms/step - loss: 0.2531 - f1_m: 0.9692 - val_loss: 0.2213 - val_f1_m: 0.9697
Epoch 9/10
1013/1013 [==============================] - 4s 4ms/step - loss: 0.2513 - f1_m: 0.9696 - val_loss: 0.2513 - val_f1_m: 0.9697
Epoch 10/10
1013/1013 [==============================] - 3s 3ms/step - loss: 0.2352 - f1_m: 0.9696 - val_loss: 0.2466 - val_f1_m: 0.9697

In [79]:
x_train_fill2, x_valid_fill2, y_train_fill2, y_valid_fill2 = train_test_split(X_fill2, Y, test_size=0.2, shuffle=True, stratify=Y, random_state=34)

history4 = model_fill2.fit(x_train_fill2, y_train_fill2, epochs=10, validation_data=(x_valid_fill2, y_valid_fill2))

Epoch 1/10
1013/1013 [==============================] - 3s 2ms/step - loss: 0.6302 - f1_m: 0.9692 - val_loss: 0.2234 - val_f1_m: 0.9697
Epoch 2/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2233 - f1_m: 0.9697 - val_loss: 0.2213 - val_f1_m: 0.9697
Epoch 3/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2239 - f1_m: 0.9696 - val_loss: 0.2265 - val_f1_m: 0.9697
Epoch 4/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2247 - f1_m: 0.9696 - val_loss: 0.2246 - val_f1_m: 0.9697
Epoch 5/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2243 - f1_m: 0.9697 - val_loss: 0.2225 - val_f1_m: 0.9697
Epoch 6/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2253 - f1_m: 0.9696 - val_loss: 0.2388 - val_f1_m: 0.9697
Epoch 7/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2243 - f1_m: 0.9696 - val_loss: 0.2235 - val_f1_m: 0.9697
Epoch 8/10
1013/1013 [==============================] - 4s 4ms/step - loss: 0.2242 - f1_m: 0.9696 - val_loss: 0.2245 - val_f1_m: 0.9697
Epoch 9/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2239 - f1_m: 0.9696 - val_loss: 0.2217 - val_f1_m: 0.9697
Epoch 10/10
1013/1013 [==============================] - 3s 3ms/step - loss: 0.2244 - f1_m: 0.9696 - val_loss: 0.2215 - val_f1_m: 0.9697

In [80]:
###학습 완료

In [81]:
test = pd.read_csv('test_data_mlp.csv')

In [82]:
X_test = test.drop(columns=['Set ID'])

In [83]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17361 entries, 0 to 17360
Data columns (total 98 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   CURE END POSITION X Collect Result_Dam                      17361 non-null  float64
 1   CURE END POSITION Z Collect Result_Dam                      17361 non-null  float64
 2   CURE END POSITION Θ Collect Result_Dam                      17361 non-null  int64
 3   CURE SPEED Collect Result_Dam                               17361 non-null  int64
 4   CURE START POSITION X Collect Result_Dam                    17361 non-null  int64
 5   CURE START POSITION Θ Collect Result_Dam                    17361 non-null  int64
 6   DISCHARGED SPEED OF RESIN Collect Result_Dam                17361 non-null  int64
 7   DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam         17361 non-null  float64
 8   DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam         17361 non-null  float64
 9   DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam         17361 non-null  float64
 10  Dispense Volume(Stage1) Collect Result_Dam                  17361 non-null  float64
 11  Dispense Volume(Stage2) Collect Result_Dam                  17361 non-null  float64
 12  Dispense Volume(Stage3) Collect Result_Dam                  17361 non-null  float64
 13  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Dam    17361 non-null  float64
 14  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Dam    17361 non-null  float64
 15  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Dam    17361 non-null  float64
 16  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam    17361 non-null  float64
 17  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Dam    17361 non-null  float64
 18  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam    17361 non-null  float64
 19  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Dam    17361 non-null  float64
 20  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Dam    17361 non-null  float64
 21  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Dam    17361 non-null  float64
 22  Head Clean Position Z Collect Result_Dam                    17361 non-null  float64
 23  Head Purge Position Z Collect Result_Dam                    17361 non-null  float64
 24  Head Zero Position Y Collect Result_Dam                     17361 non-null  float64
 25  Head Zero Position Z Collect Result_Dam                     17361 non-null  float64
 26  Machine Tact time Collect Result_Dam                        17361 non-null  float64
 27  Stage1 Circle1 Distance Speed Collect Result_Dam            17361 non-null  float64
 28  Stage1 Circle2 Distance Speed Collect Result_Dam            17361 non-null  float64
 29  Stage1 Circle3 Distance Speed Collect Result_Dam            17361 non-null  float64
 30  Stage1 Circle4 Distance Speed Collect Result_Dam            17361 non-null  float64
 31  Stage1 Line1 Distance Speed Collect Result_Dam              17361 non-null  float64
 32  Stage1 Line2 Distance Speed Collect Result_Dam              17361 non-null  float64
 33  Stage1 Line3 Distance Speed Collect Result_Dam              17361 non-null  float64
 34  Stage1 Line4 Distance Speed Collect Result_Dam              17361 non-null  float64
 35  Stage2 Circle1 Distance Speed Collect Result_Dam            17361 non-null  float64
 36  Stage2 Circle2 Distance Speed Collect Result_Dam            17361 non-null  float64
 37  Stage2 Circle3 Distance Speed Collect Result_Dam            17361 non-null  float64
 38  Stage2 Circle4 Distance Speed Collect Result_Dam            17361 non-null  float64
 39  Stage2 Line1 Distance Speed Collect Result_Dam              17361 non-null  float64
 40  Stage2 Line2 Distance Speed Collect Result_Dam              17361 non-null  float64
 41  Stage2 Line3 Distance Speed Collect Result_Dam              17361 non-null  float64
 42  Stage2 Line4 Distance Speed Collect Result_Dam              17361 non-null  float64
 43  Stage3 Circle1 Distance Speed Collect Result_Dam            17361 non-null  float64
 44  Stage3 Circle2 Distance Speed Collect Result_Dam            17361 non-null  float64
 45  Stage3 Circle3 Distance Speed Collect Result_Dam            17361 non-null  float64
 46  Stage3 Circle4 Distance Speed Collect Result_Dam            17361 non-null  float64
 47  Stage3 Line1 Distance Speed Collect Result_Dam              17361 non-null  float64
 48  Stage3 Line2 Distance Speed Collect Result_Dam              17361 non-null  float64
 49  Stage3 Line3 Distance Speed Collect Result_Dam              17361 non-null  float64
 50  Stage3 Line4 Distance Speed Collect Result_Dam              17361 non-null  float64
 51  THICKNESS 1 Collect Result_Dam                              17361 non-null  float64
 52  THICKNESS 2 Collect Result_Dam                              17361 non-null  float64
 53  THICKNESS 3 Collect Result_Dam                              17361 non-null  float64
 54  1st Pressure Collect Result_AutoClave                       17361 non-null  float64
 55  1st Pressure 1st Pressure Unit Time_AutoClave               17361 non-null  int64
 56  2nd Pressure Collect Result_AutoClave                       17361 non-null  float64
 57  2nd Pressure Unit Time_AutoClave                            17361 non-null  int64
 58  3rd Pressure Collect Result_AutoClave                       17361 non-null  float64
 59  3rd Pressure Unit Time_AutoClave                            17361 non-null  int64
 60  Chamber Temp. Collect Result_AutoClave                      17361 non-null  int64
 61  Chamber Temp. Unit Time_AutoClave                           17361 non-null  int64
 62  DISCHARGED SPEED OF RESIN Collect Result_Fill1              17361 non-null  float64
 63  DISCHARGED TIME OF RESIN(Stage1) Collect Result_Fill1       17361 non-null  float64
 64  DISCHARGED TIME OF RESIN(Stage2) Collect Result_Fill1       17361 non-null  float64
 65  DISCHARGED TIME OF RESIN(Stage3) Collect Result_Fill1       17361 non-null  float64
 66  Dispense Volume(Stage1) Collect Result_Fill1                17361 non-null  float64
 67  Dispense Volume(Stage2) Collect Result_Fill1                17361 non-null  float64
 68  Dispense Volume(Stage3) Collect Result_Fill1                17361 non-null  float64
 69  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill1  17361 non-null  float64
 70  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill1  17361 non-null  float64
 71  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill1  17361 non-null  float64
 72  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill1  17361 non-null  float64
 73  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill1  17361 non-null  float64
 74  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill1  17361 non-null  float64
 75  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill1  17361 non-null  float64
 76  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill1  17361 non-null  float64
 77  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill1  17361 non-null  float64
 78  Head Purge Position Z Collect Result_Fill1                  17361 non-null  float64
 79  Machine Tact time Collect Result_Fill1                      17361 non-null  float64
 80  CURE END POSITION X Collect Result_Fill2                    17361 non-null  int64
 81  CURE END POSITION Z Collect Result_Fill2                    17361 non-null  int64
 82  CURE SPEED Collect Result_Fill2                             17361 non-null  int64
 83  CURE STANDBY POSITION Z Collect Result_Fill2                17361 non-null  int64
 84  CURE START POSITION X Collect Result_Fill2                  17361 non-null  int64
 85  CURE START POSITION Z Collect Result_Fill2                  17361 non-null  int64
 86  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill2  17361 non-null  float64
 87  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill2  17361 non-null  float64
 88  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill2  17361 non-null  float64
 89  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill2  17361 non-null  float64
 90  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill2  17361 non-null  float64
 91  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill2  17361 non-null  float64
 92  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill2  17361 non-null  float64
 93  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill2  17361 non-null  float64
 94  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill2  17361 non-null  float64
 95  Head Purge Position Z Collect Result_Fill2                  17361 non-null  float64
 96  Machine Tact time Collect Result_Fill2                      17361 non-null  float64
 97  suffix_encoded                                              17361 non-null  int64
dtypes: float64(81), int64(17)
memory usage: 13.0 MB

In [84]:
X_test_dam = X_test.iloc[:,0:54]
X_test_dam['suffix_encoded'] = X_test['suffix_encoded']

In [85]:
X_test_autoclave = X_test.iloc[:,54:62]
X_test_autoclave['suffix_encoded'] = X_test['suffix_encoded']

In [86]:
X_test_fill1 = X_test.iloc[:,62:80]
X_test_fill1['suffix_encoded'] = X_test['suffix_encoded']

In [87]:
X_test_fill2 = X_test.iloc[:,80:]

In [88]:
X_test_SetID = test['Set ID']

In [89]:
X_test_SetID

0        0001be084fbc4aaa9d921f39e595961b
1        0005bbd180064abd99e63f9ed3e1ac80
2        000948934c4140d883d670adcb609584
3        000a6bfd02874c6296dc7b2e9c5678a7
4        0018e78ce91343678716e2ea27a51c95
                       ...
17356    ffea508b59934d689b540f95eb3fa730
17357    ffed8923c8a448a98afc641b770be153
17358    fff1e73734da40adbe805359b3efb462
17359    fff8e38bdd09470baf95f71e92075dec
17360    fffa83e0a13d4c2db4fd8bf905b517d4
Name: Set ID, Length: 17361, dtype: object

In [90]:
y_prob_dam = model_dam.predict(X_test_dam)

543/543 [==============================] - 1s 1ms/step

In [91]:
y_prob_autoclave = model_autoclave.predict(X_test_autoclave)

543/543 [==============================] - 1s 1ms/step

In [92]:
y_prob_fill1 = model_fill1.predict(X_test_fill1)

543/543 [==============================] - 1s 1ms/step

In [93]:
y_prob_fill2 = model_fill2.predict(X_test_fill2)

543/543 [==============================] - 1s 1ms/step

In [132]:
y_prob_dam

array([[0.92613494],
       [0.93523043],
       [0.90891963],
       ...,
       [0.9351726 ],
       [0.8939904 ],
       [0.93417084]], dtype=float32)

In [133]:
len(y_prob_dam)

17361

In [134]:
y_prob_autoclave

array([[0.93580276],
       [0.945621  ],
       [0.9358094 ],
       ...,
       [0.94646484],
       [0.96498895],
       [0.9358152 ]], dtype=float32)

In [135]:
len(y_prob_autoclave)

17361

In [136]:
y_prob_fill1

array([[0.9567095 ],
       [0.95966023],
       [0.85035914],
       ...,
       [0.8845842 ],
       [0.7849079 ],
       [0.8884167 ]], dtype=float32)

In [137]:
len(y_prob_fill1)

17361

In [138]:
y_prob_fill2

array([[0.94430774],
       [0.94430774],
       [0.9444155 ],
       ...,
       [0.9454419 ],
       [0.9442036 ],
       [0.9453688 ]], dtype=float32)

In [139]:
len(y_prob_fill2)

17361

In [140]:
df = pd.DataFrame(X_test_SetID)

In [141]:
df['target_dam'] = 0
df['target_autoclave'] = 0
df['target_fill1'] = 0
df['target_fill2'] = 0

In [142]:
df

,Set ID,target_dam,target_autoclave,target_fill1,target_fill2
0,0001be084fbc4aaa9d921f39e595961b,0,0,0,0
1,0005bbd180064abd99e63f9ed3e1ac80,0,0,0,0
2,000948934c4140d883d670adcb609584,0,0,0,0
3,000a6bfd02874c6296dc7b2e9c5678a7,0,0,0,0
4,0018e78ce91343678716e2ea27a51c95,0,0,0,0
...,...,...,...,...,...
17356,ffea508b59934d689b540f95eb3fa730,0,0,0,0
17357,ffed8923c8a448a98afc641b770be153,0,0,0,0
17358,fff1e73734da40adbe805359b3efb462,0,0,0,0
17359,fff8e38bdd09470baf95f71e92075dec,0,0,0,0
17360,fffa83e0a13d4c2db4fd8bf905b517d4,0,0,0,0

In [143]:
# n=0
# for i in df['target']:
#     if i > 0.9:
#         df.iloc[n,1] = 'Normal'
#     else:
#         df.iloc[n,1] = 'AbNormal'
#     n = n+1

In [144]:
df['target_dam'] = y_prob_dam

In [145]:
df['target_autoclave'] = y_prob_autoclave
df['target_fill1'] = y_prob_fill1
df['target_fill2'] = y_prob_fill2

In [146]:
df

,Set ID,target_dam,target_autoclave,target_fill1,target_fill2
0,0001be084fbc4aaa9d921f39e595961b,0.926135,0.935803,0.956710,0.944308
1,0005bbd180064abd99e63f9ed3e1ac80,0.935230,0.945621,0.959660,0.944308
2,000948934c4140d883d670adcb609584,0.908920,0.935809,0.850359,0.944416
3,000a6bfd02874c6296dc7b2e9c5678a7,0.947553,0.939673,0.951811,0.944309
4,0018e78ce91343678716e2ea27a51c95,0.932165,0.946425,0.880776,0.945399
...,...,...,...,...,...
17356,ffea508b59934d689b540f95eb3fa730,0.947436,0.937739,0.949559,0.944305
17357,ffed8923c8a448a98afc641b770be153,0.926176,0.946837,0.959711,0.944308
17358,fff1e73734da40adbe805359b3efb462,0.935173,0.946465,0.884584,0.945442
17359,fff8e38bdd09470baf95f71e92075dec,0.893990,0.964989,0.784908,0.944204
17360,fffa83e0a13d4c2db4fd8bf905b517d4,0.934171,0.935815,0.888417,0.945369

In [147]:
df['target_fill1'].value_counts()

target_fill1
0.956710    140
0.956754    133
0.959619     93
0.948367     84
0.785124     82
           ...
0.876573      1
0.878332      1
0.873103      1
0.948366      1
0.955902      1
Name: count, Length: 4481, dtype: int64

In [148]:
percentile_dam = df['target_dam'].quantile(0.2)
percentile_autoclave = df['target_autoclave'].quantile(0.2)
percentile_fill1 = df['target_fill1'].quantile(0.2)
percentile_fill2 = df['target_fill2'].quantile(0.2)


lower_dam = df[df['target_dam'] <= percentile_dam].index
lower_dam = df[df['target_autoclave'] <= percentile_autoclave].index
lower_dam = df[df['target_fill1'] <= percentile_fill1].index
lower_dam = df[df['target_fill2'] <= percentile_fill2].index

In [149]:
print(percentile_dam)
print(percentile_autoclave)
print(percentile_fill1)
print(percentile_fill2)

0.9089122414588928
0.9362919330596924
0.8105377554893494
0.9443077445030212

In [150]:
n=0
for i in df['target_dam']:
    if i > 0.9089122414588928:
        df.iloc[n,1] = 'Normal'
    else:
        df.iloc[n,1] = 'AbNormal'
    n = n+1

/tmp/ipykernel_656/2018492039.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Normal' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df.iloc[n,1] = 'Normal'

In [151]:
n=0
for i in df['target_autoclave']:
    if i > 0.9362919330596924:
        df.iloc[n,2] = 'Normal'
    else:
        df.iloc[n,2] = 'AbNormal'
    n = n+1

/tmp/ipykernel_656/2548533276.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'AbNormal' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df.iloc[n,2] = 'AbNormal'

In [152]:
n=0
for i in df['target_fill1']:
    if i > 0.8105377554893494:
        df.iloc[n,3] = 'Normal'
    else:
        df.iloc[n,3] = 'AbNormal'
    n = n+1

/tmp/ipykernel_656/2114346954.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Normal' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df.iloc[n,3] = 'Normal'

In [153]:
n=0
for i in df['target_fill2']:
    if i > 0.9443077445030212:
        df.iloc[n,4] = 'Normal'
    else:
        df.iloc[n,4] = 'AbNormal'
    n = n+1

/tmp/ipykernel_656/777138892.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'AbNormal' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df.iloc[n,4] = 'AbNormal'

In [154]:
df['target_dam'].value_counts()

target_dam
Normal      13879
AbNormal     3482
Name: count, dtype: int64

In [155]:
df['target_autoclave'].value_counts()

target_autoclave
Normal      13887
AbNormal     3474
Name: count, dtype: int64

In [156]:
df['target_fill1'].value_counts()

target_fill1
Normal      13865
AbNormal     3496
Name: count, dtype: int64

In [157]:
df['target_fill2'].value_counts()

target_fill2
Normal      13707
AbNormal     3654
Name: count, dtype: int64

In [158]:
df.head(10)

,Set ID,target_dam,target_autoclave,target_fill1,target_fill2
0,0001be084fbc4aaa9d921f39e595961b,Normal,AbNormal,Normal,AbNormal
1,0005bbd180064abd99e63f9ed3e1ac80,Normal,Normal,Normal,AbNormal
2,000948934c4140d883d670adcb609584,Normal,AbNormal,Normal,Normal
3,000a6bfd02874c6296dc7b2e9c5678a7,Normal,Normal,Normal,Normal
4,0018e78ce91343678716e2ea27a51c95,Normal,Normal,Normal,Normal
5,001fda4596f545d0a3b0ce85fbea77d2,AbNormal,AbNormal,AbNormal,Normal
6,0020734a7b29472298358ad58645a0c9,AbNormal,AbNormal,AbNormal,Normal
7,00234c5914cd4c4a888d13f8b3773135,AbNormal,AbNormal,AbNormal,Normal
8,00297b6c93e44d49ac534758a23dc74e,Normal,Normal,Normal,Normal
9,002d904240d84b188d410d16383a9c3a,Normal,Normal,Normal,AbNormal

In [159]:
columns_to_check = ['target_dam', 'target_autoclave', 'target_fill1', 'target_fill2']

In [160]:
df['target'] = df[columns_to_check].apply(lambda x: 'AbNormal' if (x == 'AbNormal').sum() >= 2 else 'Normal', axis=1)

In [161]:
df.head(10)

,Set ID,target_dam,target_autoclave,target_fill1,target_fill2,target
0,0001be084fbc4aaa9d921f39e595961b,Normal,AbNormal,Normal,AbNormal,AbNormal
1,0005bbd180064abd99e63f9ed3e1ac80,Normal,Normal,Normal,AbNormal,Normal
2,000948934c4140d883d670adcb609584,Normal,AbNormal,Normal,Normal,Normal
3,000a6bfd02874c6296dc7b2e9c5678a7,Normal,Normal,Normal,Normal,Normal
4,0018e78ce91343678716e2ea27a51c95,Normal,Normal,Normal,Normal,Normal
5,001fda4596f545d0a3b0ce85fbea77d2,AbNormal,AbNormal,AbNormal,Normal,AbNormal
6,0020734a7b29472298358ad58645a0c9,AbNormal,AbNormal,AbNormal,Normal,AbNormal
7,00234c5914cd4c4a888d13f8b3773135,AbNormal,AbNormal,AbNormal,Normal,AbNormal
8,00297b6c93e44d49ac534758a23dc74e,Normal,Normal,Normal,Normal,Normal
9,002d904240d84b188d410d16383a9c3a,Normal,Normal,Normal,AbNormal,Normal

In [162]:
df['target'].value_counts()

target
Normal      13059
AbNormal     4302
Name: count, dtype: int64

In [163]:
df = df.drop(columns=['target_dam', 'target_autoclave', 'target_fill1', 'target_fill2'])

In [164]:
df

                                 Set ID    target
0      0001be084fbc4aaa9d921f39e595961b  AbNormal
1      0005bbd180064abd99e63f9ed3e1ac80    Normal
2      000948934c4140d883d670adcb609584    Normal
3      000a6bfd02874c6296dc7b2e9c5678a7    Normal
4      0018e78ce91343678716e2ea27a51c95    Normal
...                                 ...       ...
17356  ffea508b59934d689b540f95eb3fa730    Normal
17357  ffed8923c8a448a98afc641b770be153    Normal
17358  fff1e73734da40adbe805359b3efb462    Normal
17359  fff8e38bdd09470baf95f71e92075dec  AbNormal
17360  fffa83e0a13d4c2db4fd8bf905b517d4    Normal

[17361 rows x 2 columns]

In [165]:
df['target'].value_counts()

target
Normal      13059
AbNormal     4302
Name: count, dtype: int64

In [166]:
df.to_csv("submission.csv", index=False)