In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('train_data_mlp.csv')

In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import backend as K
from sklearn.metrics import f1_score
import numpy as np

tf.random.set_seed(42)

#F1 스코어를 계산하는 사용자 정의 함수
def f1_m(y_true, y_pred):
    y_pred = K.round(y_pred)
    tp = K.sum(K.cast(y_true * y_pred, 'float'), axis=0)
    tn = K.sum(K.cast((1-y_true) * (1-y_pred), 'float'), axis=0)
    fp = K.sum(K.cast((1-y_true) * y_pred, 'float'), axis=0)
    fn = K.sum(K.cast(y_true * (1-y_pred), 'float'), axis=0)

    p = tp / (tp + fp + K.epsilon())
    r = tp / (tp + fn + K.epsilon())

    f1 = 2 * p * r / (p + r + K.epsilon())
    f1 = tf.where(tf.math.is_nan(f1), tf.zeros_like(f1), f1)
    return K.mean(f1)

# 모델 생성
model_temp = Sequential()
model_temp.add(Dense(50, input_dim=98, activation='relu'))
model_temp.add(Dense(30, activation='relu'))
model_temp.add(Dense(10, activation='relu'))
model_temp.add(Dense(1, activation='sigmoid'))

# F1 스코어를 평가지표로 사용
model_temp.compile(optimizer='adam', loss='binary_crossentropy', metrics=[f1_m])

model_temp.summary()

2024-08-13 05:06:33.496492: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-13 05:06:33.800529: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-13 05:06:33.800602: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-13 05:06:33.830634: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-13 05:06:33.905180: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-13 05:06:35.235651: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                4950

 dense_1 (Dense)             (None, 30)                1530

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 6801 (26.57 KB)
Trainable params: 6801 (26.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [3]:
X = df.drop(columns=['target'])
Y = df['target']

In [4]:
X

,CURE END POSITION X Collect Result_Dam,CURE END POSITION Z Collect Result_Dam,CURE END POSITION Θ Collect Result_Dam,CURE SPEED Collect Result_Dam,CURE START POSITION X Collect Result_Dam,CURE START POSITION Θ Collect Result_Dam,DISCHARGED SPEED OF RESIN Collect Result_Dam,DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam,DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam,DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam,...,HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill2,HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill2,HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill2,Head Purge Position Z Collect Result_Fill2,Machine Tact time Collect Result_Fill2,suffix_encoded
0,240.0,2.5,-90,100,1030,-90,16,14.9,8.4,14.7,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,114.612,19.9,3
1,240.0,2.5,-90,70,1030,-90,10,21.3,4.9,21.3,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.6,3
2,1000.0,12.5,90,85,280,90,16,14.7,8.5,14.7,...,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,114.612,19.8,0
3,1000.0,12.5,90,70,280,90,10,21.3,8.4,21.3,...,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,85.000,19.9,0
4,240.0,2.5,-90,70,1030,-90,10,9.7,4.9,9.6,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,240.0,2.5,-90,70,1030,-90,10,17.0,5.0,17.0,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.2,0
40502,1000.0,12.5,90,100,280,90,16,14.9,8.5,14.7,...,692.8,1324.2,1324.2,1324.2,243.5,243.5,243.5,114.612,20.5,0
40503,240.0,2.5,-90,100,1030,-90,16,14.2,8.2,14.3,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.7,0
40504,1000.0,12.5,90,70,280,90,10,9.7,4.9,9.7,...,694.0,1324.2,1324.2,1324.2,243.5,243.5,243.5,85.000,20.1,0
40505,240.0,2.5,-90,70,1030,-90,10,9.6,3.9,9.7,...,156.0,428.0,427.9,428.0,243.7,243.7,243.7,85.000,19.4,0

In [5]:
Y

0        1
1        1
2        1
3        1
4        1
        ..
40501    1
40502    1
40503    1
40504    1
40505    0
Name: target, Length: 40506, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40506 entries, 0 to 40505
Data columns (total 99 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   CURE END POSITION X Collect Result_Dam                      40506 non-null  float64
 1   CURE END POSITION Z Collect Result_Dam                      40506 non-null  float64
 2   CURE END POSITION Θ Collect Result_Dam                      40506 non-null  int64
 3   CURE SPEED Collect Result_Dam                               40506 non-null  int64
 4   CURE START POSITION X Collect Result_Dam                    40506 non-null  int64
 5   CURE START POSITION Θ Collect Result_Dam                    40506 non-null  int64
 6   DISCHARGED SPEED OF RESIN Collect Result_Dam                40506 non-null  int64
 7   DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam         40506 non-null  float64
 8   DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam         40506 non-null  float64
 9   DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam         40506 non-null  float64
 10  Dispense Volume(Stage1) Collect Result_Dam                  40506 non-null  float64
 11  Dispense Volume(Stage2) Collect Result_Dam                  40506 non-null  float64
 12  Dispense Volume(Stage3) Collect Result_Dam                  40506 non-null  float64
 13  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Dam    40506 non-null  float64
 14  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Dam    40506 non-null  float64
 15  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Dam    40506 non-null  float64
 16  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam    40506 non-null  float64
 17  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Dam    40506 non-null  float64
 18  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam    40506 non-null  float64
 19  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Dam    40506 non-null  float64
 20  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Dam    40506 non-null  float64
 21  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Dam    40506 non-null  float64
 22  Head Clean Position Z Collect Result_Dam                    40506 non-null  float64
 23  Head Purge Position Z Collect Result_Dam                    40506 non-null  float64
 24  Head Zero Position Y Collect Result_Dam                     40506 non-null  float64
 25  Head Zero Position Z Collect Result_Dam                     40506 non-null  float64
 26  Machine Tact time Collect Result_Dam                        40506 non-null  float64
 27  Stage1 Circle1 Distance Speed Collect Result_Dam            40506 non-null  float64
 28  Stage1 Circle2 Distance Speed Collect Result_Dam            40506 non-null  float64
 29  Stage1 Circle3 Distance Speed Collect Result_Dam            40506 non-null  float64
 30  Stage1 Circle4 Distance Speed Collect Result_Dam            40506 non-null  float64
 31  Stage1 Line1 Distance Speed Collect Result_Dam              40506 non-null  float64
 32  Stage1 Line2 Distance Speed Collect Result_Dam              40506 non-null  float64
 33  Stage1 Line3 Distance Speed Collect Result_Dam              40506 non-null  float64
 34  Stage1 Line4 Distance Speed Collect Result_Dam              40506 non-null  float64
 35  Stage2 Circle1 Distance Speed Collect Result_Dam            40506 non-null  float64
 36  Stage2 Circle2 Distance Speed Collect Result_Dam            40506 non-null  float64
 37  Stage2 Circle3 Distance Speed Collect Result_Dam            40506 non-null  float64
 38  Stage2 Circle4 Distance Speed Collect Result_Dam            40506 non-null  float64
 39  Stage2 Line1 Distance Speed Collect Result_Dam              40506 non-null  float64
 40  Stage2 Line2 Distance Speed Collect Result_Dam              40506 non-null  float64
 41  Stage2 Line3 Distance Speed Collect Result_Dam              40506 non-null  float64
 42  Stage2 Line4 Distance Speed Collect Result_Dam              40506 non-null  float64
 43  Stage3 Circle1 Distance Speed Collect Result_Dam            40506 non-null  float64
 44  Stage3 Circle2 Distance Speed Collect Result_Dam            40506 non-null  float64
 45  Stage3 Circle3 Distance Speed Collect Result_Dam            40506 non-null  float64
 46  Stage3 Circle4 Distance Speed Collect Result_Dam            40506 non-null  float64
 47  Stage3 Line1 Distance Speed Collect Result_Dam              40506 non-null  float64
 48  Stage3 Line2 Distance Speed Collect Result_Dam              40506 non-null  float64
 49  Stage3 Line3 Distance Speed Collect Result_Dam              40506 non-null  float64
 50  Stage3 Line4 Distance Speed Collect Result_Dam              40506 non-null  float64
 51  THICKNESS 1 Collect Result_Dam                              40506 non-null  float64
 52  THICKNESS 2 Collect Result_Dam                              40506 non-null  float64
 53  THICKNESS 3 Collect Result_Dam                              40506 non-null  float64
 54  1st Pressure Collect Result_AutoClave                       40506 non-null  float64
 55  1st Pressure 1st Pressure Unit Time_AutoClave               40506 non-null  int64
 56  2nd Pressure Collect Result_AutoClave                       40506 non-null  float64
 57  2nd Pressure Unit Time_AutoClave                            40506 non-null  int64
 58  3rd Pressure Collect Result_AutoClave                       40506 non-null  float64
 59  3rd Pressure Unit Time_AutoClave                            40506 non-null  int64
 60  Chamber Temp. Collect Result_AutoClave                      40506 non-null  int64
 61  Chamber Temp. Unit Time_AutoClave                           40506 non-null  int64
 62  DISCHARGED SPEED OF RESIN Collect Result_Fill1              40506 non-null  float64
 63  DISCHARGED TIME OF RESIN(Stage1) Collect Result_Fill1       40506 non-null  float64
 64  DISCHARGED TIME OF RESIN(Stage2) Collect Result_Fill1       40506 non-null  float64
 65  DISCHARGED TIME OF RESIN(Stage3) Collect Result_Fill1       40506 non-null  float64
 66  Dispense Volume(Stage1) Collect Result_Fill1                40506 non-null  float64
 67  Dispense Volume(Stage2) Collect Result_Fill1                40506 non-null  float64
 68  Dispense Volume(Stage3) Collect Result_Fill1                40506 non-null  float64
 69  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill1  40506 non-null  float64
 70  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill1  40506 non-null  float64
 71  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill1  40506 non-null  float64
 72  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill1  40506 non-null  float64
 73  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill1  40506 non-null  float64
 74  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill1  40506 non-null  float64
 75  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill1  40506 non-null  float64
 76  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill1  40506 non-null  float64
 77  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill1  40506 non-null  float64
 78  Head Purge Position Z Collect Result_Fill1                  40506 non-null  float64
 79  Machine Tact time Collect Result_Fill1                      40506 non-null  float64
 80  CURE END POSITION X Collect Result_Fill2                    40506 non-null  int64
 81  CURE END POSITION Z Collect Result_Fill2                    40506 non-null  int64
 82  CURE SPEED Collect Result_Fill2                             40506 non-null  int64
 83  CURE STANDBY POSITION Z Collect Result_Fill2                40506 non-null  int64
 84  CURE START POSITION X Collect Result_Fill2                  40506 non-null  int64
 85  CURE START POSITION Z Collect Result_Fill2                  40506 non-null  int64
 86  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill2  40506 non-null  float64
 87  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill2  40506 non-null  float64
 88  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill2  40506 non-null  float64
 89  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill2  40506 non-null  float64
 90  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill2  40506 non-null  float64
 91  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill2  40506 non-null  float64
 92  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill2  40506 non-null  float64
 93  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill2  40506 non-null  float64
 94  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill2  40506 non-null  float64
 95  Head Purge Position Z Collect Result_Fill2                  40506 non-null  float64
 96  Machine Tact time Collect Result_Fill2                      40506 non-null  float64
 97  target                                                      40506 non-null  int64
 98  suffix_encoded                                              40506 non-null  int64
dtypes: float64(81), int64(18)
memory usage: 30.6 MB

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(X, Y, test_size=0.2, shuffle=True, stratify=Y, random_state=34)

In [8]:
history = model_temp.fit(x_train, y_train, epochs=10, validation_data=(x_valid, y_valid))

Epoch 1/10
1013/1013 [==============================] - 3s 2ms/step - loss: 5.0201 - f1_m: 0.9240 - val_loss: 1.0749 - val_f1_m: 0.9697
Epoch 2/10
1013/1013 [==============================] - 2s 2ms/step - loss: 1.7552 - f1_m: 0.9288 - val_loss: 1.0937 - val_f1_m: 0.9697
Epoch 3/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.7784 - f1_m: 0.9450 - val_loss: 0.5218 - val_f1_m: 0.9697
Epoch 4/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.5696 - f1_m: 0.9484 - val_loss: 0.5183 - val_f1_m: 0.9697
Epoch 5/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.4500 - f1_m: 0.9539 - val_loss: 0.2597 - val_f1_m: 0.9697
Epoch 6/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.3097 - f1_m: 0.9642 - val_loss: 0.2373 - val_f1_m: 0.9697
Epoch 7/10
1013/1013 [==============================] - 3s 2ms/step - loss: 0.2766 - f1_m: 0.9669 - val_loss: 0.3272 - val_f1_m: 0.9697
Epoch 8/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2653 - f1_m: 0.9676 - val_loss: 0.2291 - val_f1_m: 0.9697
Epoch 9/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2482 - f1_m: 0.9693 - val_loss: 0.2837 - val_f1_m: 0.9697
Epoch 10/10
1013/1013 [==============================] - 2s 2ms/step - loss: 0.2667 - f1_m: 0.9678 - val_loss: 0.2334 - val_f1_m: 0.9697

In [9]:
test = pd.read_csv('test_data_mlp.csv')

In [10]:
X_test = test.drop(columns=['Set ID'])

In [11]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17361 entries, 0 to 17360
Data columns (total 98 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   CURE END POSITION X Collect Result_Dam                      17361 non-null  float64
 1   CURE END POSITION Z Collect Result_Dam                      17361 non-null  float64
 2   CURE END POSITION Θ Collect Result_Dam                      17361 non-null  int64
 3   CURE SPEED Collect Result_Dam                               17361 non-null  int64
 4   CURE START POSITION X Collect Result_Dam                    17361 non-null  int64
 5   CURE START POSITION Θ Collect Result_Dam                    17361 non-null  int64
 6   DISCHARGED SPEED OF RESIN Collect Result_Dam                17361 non-null  int64
 7   DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam         17361 non-null  float64
 8   DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam         17361 non-null  float64
 9   DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam         17361 non-null  float64
 10  Dispense Volume(Stage1) Collect Result_Dam                  17361 non-null  float64
 11  Dispense Volume(Stage2) Collect Result_Dam                  17361 non-null  float64
 12  Dispense Volume(Stage3) Collect Result_Dam                  17361 non-null  float64
 13  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Dam    17361 non-null  float64
 14  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Dam    17361 non-null  float64
 15  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Dam    17361 non-null  float64
 16  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam    17361 non-null  float64
 17  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Dam    17361 non-null  float64
 18  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam    17361 non-null  float64
 19  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Dam    17361 non-null  float64
 20  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Dam    17361 non-null  float64
 21  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Dam    17361 non-null  float64
 22  Head Clean Position Z Collect Result_Dam                    17361 non-null  float64
 23  Head Purge Position Z Collect Result_Dam                    17361 non-null  float64
 24  Head Zero Position Y Collect Result_Dam                     17361 non-null  float64
 25  Head Zero Position Z Collect Result_Dam                     17361 non-null  float64
 26  Machine Tact time Collect Result_Dam                        17361 non-null  float64
 27  Stage1 Circle1 Distance Speed Collect Result_Dam            17361 non-null  float64
 28  Stage1 Circle2 Distance Speed Collect Result_Dam            17361 non-null  float64
 29  Stage1 Circle3 Distance Speed Collect Result_Dam            17361 non-null  float64
 30  Stage1 Circle4 Distance Speed Collect Result_Dam            17361 non-null  float64
 31  Stage1 Line1 Distance Speed Collect Result_Dam              17361 non-null  float64
 32  Stage1 Line2 Distance Speed Collect Result_Dam              17361 non-null  float64
 33  Stage1 Line3 Distance Speed Collect Result_Dam              17361 non-null  float64
 34  Stage1 Line4 Distance Speed Collect Result_Dam              17361 non-null  float64
 35  Stage2 Circle1 Distance Speed Collect Result_Dam            17361 non-null  float64
 36  Stage2 Circle2 Distance Speed Collect Result_Dam            17361 non-null  float64
 37  Stage2 Circle3 Distance Speed Collect Result_Dam            17361 non-null  float64
 38  Stage2 Circle4 Distance Speed Collect Result_Dam            17361 non-null  float64
 39  Stage2 Line1 Distance Speed Collect Result_Dam              17361 non-null  float64
 40  Stage2 Line2 Distance Speed Collect Result_Dam              17361 non-null  float64
 41  Stage2 Line3 Distance Speed Collect Result_Dam              17361 non-null  float64
 42  Stage2 Line4 Distance Speed Collect Result_Dam              17361 non-null  float64
 43  Stage3 Circle1 Distance Speed Collect Result_Dam            17361 non-null  float64
 44  Stage3 Circle2 Distance Speed Collect Result_Dam            17361 non-null  float64
 45  Stage3 Circle3 Distance Speed Collect Result_Dam            17361 non-null  float64
 46  Stage3 Circle4 Distance Speed Collect Result_Dam            17361 non-null  float64
 47  Stage3 Line1 Distance Speed Collect Result_Dam              17361 non-null  float64
 48  Stage3 Line2 Distance Speed Collect Result_Dam              17361 non-null  float64
 49  Stage3 Line3 Distance Speed Collect Result_Dam              17361 non-null  float64
 50  Stage3 Line4 Distance Speed Collect Result_Dam              17361 non-null  float64
 51  THICKNESS 1 Collect Result_Dam                              17361 non-null  float64
 52  THICKNESS 2 Collect Result_Dam                              17361 non-null  float64
 53  THICKNESS 3 Collect Result_Dam                              17361 non-null  float64
 54  1st Pressure Collect Result_AutoClave                       17361 non-null  float64
 55  1st Pressure 1st Pressure Unit Time_AutoClave               17361 non-null  int64
 56  2nd Pressure Collect Result_AutoClave                       17361 non-null  float64
 57  2nd Pressure Unit Time_AutoClave                            17361 non-null  int64
 58  3rd Pressure Collect Result_AutoClave                       17361 non-null  float64
 59  3rd Pressure Unit Time_AutoClave                            17361 non-null  int64
 60  Chamber Temp. Collect Result_AutoClave                      17361 non-null  int64
 61  Chamber Temp. Unit Time_AutoClave                           17361 non-null  int64
 62  DISCHARGED SPEED OF RESIN Collect Result_Fill1              17361 non-null  float64
 63  DISCHARGED TIME OF RESIN(Stage1) Collect Result_Fill1       17361 non-null  float64
 64  DISCHARGED TIME OF RESIN(Stage2) Collect Result_Fill1       17361 non-null  float64
 65  DISCHARGED TIME OF RESIN(Stage3) Collect Result_Fill1       17361 non-null  float64
 66  Dispense Volume(Stage1) Collect Result_Fill1                17361 non-null  float64
 67  Dispense Volume(Stage2) Collect Result_Fill1                17361 non-null  float64
 68  Dispense Volume(Stage3) Collect Result_Fill1                17361 non-null  float64
 69  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill1  17361 non-null  float64
 70  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill1  17361 non-null  float64
 71  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill1  17361 non-null  float64
 72  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill1  17361 non-null  float64
 73  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill1  17361 non-null  float64
 74  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill1  17361 non-null  float64
 75  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill1  17361 non-null  float64
 76  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill1  17361 non-null  float64
 77  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill1  17361 non-null  float64
 78  Head Purge Position Z Collect Result_Fill1                  17361 non-null  float64
 79  Machine Tact time Collect Result_Fill1                      17361 non-null  float64
 80  CURE END POSITION X Collect Result_Fill2                    17361 non-null  int64
 81  CURE END POSITION Z Collect Result_Fill2                    17361 non-null  int64
 82  CURE SPEED Collect Result_Fill2                             17361 non-null  int64
 83  CURE STANDBY POSITION Z Collect Result_Fill2                17361 non-null  int64
 84  CURE START POSITION X Collect Result_Fill2                  17361 non-null  int64
 85  CURE START POSITION Z Collect Result_Fill2                  17361 non-null  int64
 86  HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Fill2  17361 non-null  float64
 87  HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Fill2  17361 non-null  float64
 88  HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Fill2  17361 non-null  float64
 89  HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Fill2  17361 non-null  float64
 90  HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Fill2  17361 non-null  float64
 91  HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Fill2  17361 non-null  float64
 92  HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Fill2  17361 non-null  float64
 93  HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Fill2  17361 non-null  float64
 94  HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Fill2  17361 non-null  float64
 95  Head Purge Position Z Collect Result_Fill2                  17361 non-null  float64
 96  Machine Tact time Collect Result_Fill2                      17361 non-null  float64
 97  suffix_encoded                                              17361 non-null  int64
dtypes: float64(81), int64(17)
memory usage: 13.0 MB

In [12]:
X_test_SetID = test['Set ID']

In [13]:
X_test_SetID

0        0001be084fbc4aaa9d921f39e595961b
1        0005bbd180064abd99e63f9ed3e1ac80
2        000948934c4140d883d670adcb609584
3        000a6bfd02874c6296dc7b2e9c5678a7
4        0018e78ce91343678716e2ea27a51c95
                       ...
17356    ffea508b59934d689b540f95eb3fa730
17357    ffed8923c8a448a98afc641b770be153
17358    fff1e73734da40adbe805359b3efb462
17359    fff8e38bdd09470baf95f71e92075dec
17360    fffa83e0a13d4c2db4fd8bf905b517d4
Name: Set ID, Length: 17361, dtype: object

In [15]:
y_prob = model_temp.predict(X_test)

543/543 [==============================] - 1s 1ms/step

In [49]:
y_prob

array([[0.967869  ],
       [0.9615492 ],
       [0.9742134 ],
       ...,
       [0.96848065],
       [0.9793837 ],
       [0.97148204]], dtype=float32)

In [50]:
len(y_prob)

17361

In [51]:
df = pd.DataFrame(X_test_SetID)

In [52]:
df['target'] = 0

In [53]:
df

                                 Set ID  target
0      0001be084fbc4aaa9d921f39e595961b       0
1      0005bbd180064abd99e63f9ed3e1ac80       0
2      000948934c4140d883d670adcb609584       0
3      000a6bfd02874c6296dc7b2e9c5678a7       0
4      0018e78ce91343678716e2ea27a51c95       0
...                                 ...     ...
17356  ffea508b59934d689b540f95eb3fa730       0
17357  ffed8923c8a448a98afc641b770be153       0
17358  fff1e73734da40adbe805359b3efb462       0
17359  fff8e38bdd09470baf95f71e92075dec       0
17360  fffa83e0a13d4c2db4fd8bf905b517d4       0

[17361 rows x 2 columns]

In [54]:
df['target'] = y_prob

In [55]:
df

                                 Set ID    target
0      0001be084fbc4aaa9d921f39e595961b  0.967869
1      0005bbd180064abd99e63f9ed3e1ac80  0.961549
2      000948934c4140d883d670adcb609584  0.974213
3      000a6bfd02874c6296dc7b2e9c5678a7  0.949758
4      0018e78ce91343678716e2ea27a51c95  0.970225
...                                 ...       ...
17356  ffea508b59934d689b540f95eb3fa730  0.949354
17357  ffed8923c8a448a98afc641b770be153  0.969044
17358  fff1e73734da40adbe805359b3efb462  0.968481
17359  fff8e38bdd09470baf95f71e92075dec  0.979384
17360  fffa83e0a13d4c2db4fd8bf905b517d4  0.971482

[17361 rows x 2 columns]

In [56]:
# n=0
# for i in df['target']:
#     if i > 0.9:
#         df.iloc[n,1] = 'Normal'
#     else:
#         df.iloc[n,1] = 'AbNormal'
#     n = n+1

In [57]:
df.iloc[0,1]

0.967869

In [58]:
df

                                 Set ID    target
0      0001be084fbc4aaa9d921f39e595961b  0.967869
1      0005bbd180064abd99e63f9ed3e1ac80  0.961549
2      000948934c4140d883d670adcb609584  0.974213
3      000a6bfd02874c6296dc7b2e9c5678a7  0.949758
4      0018e78ce91343678716e2ea27a51c95  0.970225
...                                 ...       ...
17356  ffea508b59934d689b540f95eb3fa730  0.949354
17357  ffed8923c8a448a98afc641b770be153  0.969044
17358  fff1e73734da40adbe805359b3efb462  0.968481
17359  fff8e38bdd09470baf95f71e92075dec  0.979384
17360  fffa83e0a13d4c2db4fd8bf905b517d4  0.971482

[17361 rows x 2 columns]

In [59]:
df['target'].value_counts()

target
0.979241    7
0.972847    6
0.979280    6
0.979282    6
0.979284    6
           ..
0.974962    1
0.979368    1
0.979295    1
0.963772    1
0.962368    1
Name: count, Length: 14854, dtype: int64

In [60]:
percentile_5 = df['target'].quantile(0.5)

lower_5_percent = df[df['target'] <= percentile_5].index

print(lower_5_percent)

Index([    1,     3,     8,     9,    10,    11,    12,    13,    17,    18,
       ...
       17342, 17344, 17346, 17347, 17348, 17349, 17351, 17352, 17354, 17356],
      dtype='int64', length=8681)

In [61]:
percentile_5

0.967805027961731

In [62]:
n=0
for i in df['target']:
    if i > 0.967805027961731:
        df.iloc[n,1] = 'Normal'
    else:
        df.iloc[n,1] = 'AbNormal'
    n = n+1

/tmp/ipykernel_17673/3822939363.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Normal' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df.iloc[n,1] = 'Normal'

In [63]:
df['target'].value_counts()

target
AbNormal    8681
Normal      8680
Name: count, dtype: int64

In [64]:
df.head(10)

                             Set ID    target
0  0001be084fbc4aaa9d921f39e595961b    Normal
1  0005bbd180064abd99e63f9ed3e1ac80  AbNormal
2  000948934c4140d883d670adcb609584    Normal
3  000a6bfd02874c6296dc7b2e9c5678a7  AbNormal
4  0018e78ce91343678716e2ea27a51c95    Normal
5  001fda4596f545d0a3b0ce85fbea77d2    Normal
6  0020734a7b29472298358ad58645a0c9    Normal
7  00234c5914cd4c4a888d13f8b3773135    Normal
8  00297b6c93e44d49ac534758a23dc74e  AbNormal
9  002d904240d84b188d410d16383a9c3a  AbNormal

In [167]:
df.to_csv("submission.csv", index=False)

In [141]:
#코드 제출 성능 f1 score 0.99